config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users,
             controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :projects do
    resources :tasks do
      member do
        patch :assign
      end
    end
  end

  resources :assigned_tasks, only: %i[index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assigned_task.rb
# frozen_string_literal: true

class AssignedTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_one :task, dependent: :destroy

  validates :longitude, :latitude, presence: true

  before_validation :set_coords_and_address

  def nearest_address
    results = Geocoder.search([coords.y, coords.x])

    results.first.address
  end

  private

  def set_coords_and_address
    self.coords = "POINT(#{longitude} #{latitude})"
    self.coords = "SRID=4326;#{coords}"
    self.address = nearest_address if coords
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  PRIORITIES = {
    low: 'low',
    high: 'high',
    urgent: 'urgent',
    normal: 'normal'
  }.freeze

  enum priority: PRIORITIES

  belongs_to :user
  belongs_to :project
  belongs_to :location, optional: true
  has_one :assigned_task, dependent: :destroy

  has_rich_text :description

  def add_location(address)
    return if address.blank?

    results = Geocoder.search(address)

    return if results.first.blank?

    coordinates = results.first.coordinates
    location = Location.where(latitude: coordinates[0], longitude: coordinates[1]).first_or_create!

    # rubocop:disable Rails/SkipsModelValidations
    update_column :location_id, location.id
    # rubocop:enable Rails/SkipsModelValidations
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :assigned_tasks, dependent: :destroy
  has_many :created_tasks, class_name: 'Task', dependent: :destroy

  validates :first_name, :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end

  def assigned_task_locations
    assigned_tasks.includes(task: :location).map do |at|
      [at.task.location&.latitude, at.task.location&.longitude].compact_blank
    end.compact_blank
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/assigned_tasks_controller.rb
# frozen_string_literal: true

class AssignedTasksController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :fetch_project, only: %i[edit update show]

  def index
    @projects = current_user.projects
  end

  def show; end

  def new
    @project = current_user.projects.new
    @project.tasks.build
  end

  def edit; end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      flash[:notice] = t('controllers.create_success', object_name: 'Project')
      redirect_to projects_path
    else
      flash[:alert] = @project.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      render :update
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:title,
                                    tasks_attributes: %i[id title user_id description priority])
  end

  def fetch_project
    @project = current_user.projects.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :fetch_task, only: %i[edit update show destroy assign]
  after_action :add_location, only: %i[create update]

  def show; end

  def new
    @task = project.tasks.new
  end

  def edit; end

  def create
    @task = project.tasks.new(task_params)

    if @task.save
      flash[:notice] = t('controllers.create_success', object_name: 'Task')
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @task.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      render :update
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @task.destroy
      flash[:notice] = t('controllers.delete_success', object_name: 'Task')
    else
      flash[:alert] = @task.errors.full_messages.to_sentence
    end

    redirect_back(fallback_location: root_path)
  end

  def assign
    assigned_task = AssignedTask.find_or_initialize_by(task: @task)

    assigned_task.update!(user_id: params[:user_id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :user_id, :description, :priority)
  end

  def fetch_task
    @task = project.tasks.find(params[:id])
  end

  def project
    @project ||= Project.find(params[:project_id])
  end

  def add_location
    @task.add_location(params[:location])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create] # rubocop:disable Rails/LexicallyScopedActionFilter
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def priority_color(priority)
    case priority
    when Task::PRIORITIES[:low] then 'text-teal-100'
    when Task::PRIORITIES[:urgent] then 'text-red-500'
    when Task::PRIORITIES[:high] then 'text-yellow-300'
    when Task::PRIORITIES[:normal] then 'text-blue-300'
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <% if blob.video? %>
    <%= video_tag url_for(blob.attachable),
    preload: "auto",
    controls: "controls",
    width: "640",
    height: "360" %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/assigned_tasks/index.html.erb
<div>
  <% current_user.assigned_tasks.each do |assigned_task| %>
    <div class="bg-gray-100 hover:bg-gray-300 block py-2 px-2  rounded-md my-2">
      <div class="grid grid-cols-8 gap-4">
        <div class="col-span-3">
          <h3 class="font-bold">Title + Description</h3>
        </div>
        <div class="col-span-1">
          <h3 class="font-bold">Assignee</h3>
        </div>
        <div class="col-span-1">
          <h3 class="font-bold">Priority</h3>
        </div>
        <div class="col-span-1">
          <h3 class="font-bold">Location</h3>
        </div>
        <div class="col-span-2">
          <h3 class="font-bold">Attachements</h3>
        </div>
      </div>
      <hr/>
      <div class="grid grid-cols-8 gap-4 mt-1">
        <div class="col-span-3">
          <div class="font-bold">
            <%= assigned_task.task.title %>
          </div>
          <div class="block">
            <%= assigned_task.task.description.to_plain_text %>
          </div>
        </div>
        <div class="col-span-1">
          <%= assigned_task.user.name %>
        </div>
        <div class="col-span-1 -my-1">
          <i class="fa-solid fa-flag text-xl mt-2 <%= priority_color(assigned_task.task.priority) %>"></i>
          <span class="pl-2 pr-3 -my-1 -mt-1 text-base"><%= assigned_task.task.priority.titleize %></span>
        </div>
        <div class="col-span-1 -my-1">
          <% if assigned_task.task.location %>
            <%= assigned_task.task.location.address %>
          <% end %>
        </div>
        <div class="col-span-2">
          <% assigned_task.task.description&.body&.attachments&.each do |attachment| %>
            <% if attachment.image? %>
              <%= image_tag attachment.variant(resize: "300x300") %>
            <% elsif attachment.video? %>
              <%= video_tag url_for(attachment.attachable),
                            preload: "auto",
                            controls: "controls",
                            width: "640",
                            height: "360" %>
            <% else %>
              <figcaption class="attachment__caption">
                <% if caption = attachment.try(:caption) %>
                  <%= caption %>
                <% else %>
                  <span class="attachment__name"><%= attachment.filename %></span>
                  <span class="attachment__size"><%= number_to_human_size attachment.byte_size %></span>
                <% end %>
              </figcaption>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div data-controller="maps">
    <h2 class="text-xl mt-6 mb-6 font-bold">Assigned Task on Map</h2>
    <div data-maps-target="container" class="h-[25rem] mb-12 w-auto" data-coordinates="<%= current_user.assigned_task_locations %>"></div>
  </div>
</div>

app/views/layouts/_flash_toastr.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>'](
        '<%= f[1] %>', '', {
        "closeButton": true,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "progressBar": true,
        "hideMethod": "fadeOut"
      });
    <% end %>
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-green-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
    <%= link_to root_path do %>
      <span class="font-semibold text-xl tracking-tight">Yammam</span>
    <% end %>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-white border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <%= link_to projects_path, class: "block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4" do %>
        Projects
      <% end %>
      <%= link_to assigned_tasks_path, class: "block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4" do %>
        Assigned Tasks
      <% end %>
    </div>
    <div>
      <%= button_to destroy_user_session_path, method: :delete, class:"inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0", role:"menuitem", tabindex:"-1", id:"user-menu-item-2" do %>
        Logout
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-geosearch@3.0.0/dist/geosearch.css"/>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "jquery" %>
  </head>

  <body>
    <%= render 'layouts/navbar' if user_signed_in? %>
    <%= turbo_frame_tag 'flash-message' do %>
      <%= render 'layouts/flash_toastr' %>
    <% end %>
    </div>
    <main class="container mx-auto mt-28">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<% unless @project.persisted? %>
  <%= link_to "Back", projects_path, class: 'bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded' %>
<% end %>

<%= simple_form_for @project do |f| %>
  <div class="card-body p-md-4 p-2">
    <div class="form-group">
      <%= f.input :title, label: 'Project Title', placeholder: 'Enter project title', input_html: { class: 'form-control rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm mt-2' } %>
      <span class="text-error"><%= @project.errors.full_messages.to_sentence %></span>
    </div>
    <% unless @project.persisted? %>
      <h3 class="text-xl mt-2 ">Tasks</h3>
      <div id="tasks">
        <%= f.simple_fields_for :tasks do |task| %>
          <%= render "task_fields", f: task %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add Task', f, :tasks, class: 'bg-green-500 hover:bg-green-600 text-white font-bold py-1 px-4 rounded inline-block mt-2' %>
        </div>
      </div>
    <% end %>
    <div class="text-right mt-4">
      <button class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">Save</button>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= turbo_frame_tag dom_id(@project, 'title') do %>
  <%= render 'form' %>
<% end %>

app/views/projects/index.html.erb
<div id="projects-section">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Projects</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the projects.</p>
    </div>
  </div>
  <div class="mt-8 flex flex-col">
    <div>
      <div class="block py-2 align-middle w-[1240px] mx-auto max-w-full">
        <div class="mb-8">
          <%= link_to new_project_path, class: 'inline-block bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-2 rounded mt-4' do %>
            <%= image_tag('add-project.svg', alt: 'icon', class: 'float-left mt-1') %>
            <span class="ml-2">Add Project</span>
          <% end %>
        </div>
        <div class="border-t border-t overflow-auto w-full relative pb-12 min-h-[480px]">

          <div class="flex items-center">
            <%= tag.turbo_frame id: "action_notice", class: "ml-4 text-green-500" %>
          </div>

          <div class="w-full block mt-2">
            <% @projects.each_with_index do |project, index| %>
              <%= link_to project_path(project), class: ' bg-gray-200 hover:bg-gray-300 block py-2 px-2  rounded-md my-2' do %>
                <span class="ml-2"><%= project.title %></span>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h2 class="text-xl mb-4 font-bold">Add new Project</h2>
<hr class="mb-6">
<%= render 'form' %>

app/views/projects/show.html.erb
<%= turbo_frame_tag dom_id(@project) do %>
  <%= link_to "Back", projects_path, data: { turbo_frame: '_top' }, class: 'bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded float-right' %>

  <%= link_to "Add new task", new_project_task_path(@project), data: { turbo_frame: 'new_task_section' }, class: 'bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded' %>

  <%= turbo_frame_tag "new_task_section" %>

  <%= turbo_frame_tag dom_id(@project, 'title') do %>
    <span class="block font-bold mt-6 text-xl">
      <%= @project.title %>
      <%= link_to edit_project_path(@project), data: { class: "hover:bg-inherit visited:text-black hover:bg-inherit visited:bg-inherit", turbo_frame: "#{dom_id(@project, 'title')}" } do %>
        <span class="ml-2"><i class="fa-solid fa-pencil"></i></span>
      <% end %>
    </span>
    <hr class="mb-6">
  <% end %>
  <% @project.tasks.each do |task| %>
    <%= turbo_frame_tag dom_id(task) do %>
      <%= render task %>
    <% end %>
  <% end %>
<% end %>

app/views/projects/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@project, 'title') do %>
  <span class='block font-bold mt-6 text-xl'>
    <%= @project.title %>
    <%= link_to edit_project_path(@project), data: { class: "hover:bg-inherit visited:text-black hover:bg-inherit visited:bg-inherit", turbo_frame: "#{dom_id(@project, 'title')}" } do %>
      <span class="ml-2"><i class="fa-solid fa-pencil"></i></span>
    <% end %>
  </span>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for([@project, @task]) do |f| %>
  <div class="flex">
    <div class="title-value w-full p-2 border round-md my-2">
      <div class="grid grid-cols-8 gap-4">
        <div class="col-span-6">
          <%= f.label :title, "Title", class:'text-base' %>
          <%= f.input :title, label: false, placeholder: 'Enter here', input_html: { class: 'w-full p-3 focus:outline-none border-slate-200 rounded-md text-sm', rows: "1" }, autocomplete: 'off' %>
          <span class="text-error"><%= f.object.errors[:title].join(", ") %></span>
        </div>

        <div class="col-span-1">
          <% if @task.persisted? %>
            <%= turbo_frame_tag 'assignee-drop-down' do %>
              <%= label_tag :assignee, "Assignee", class:'text-base' %>
              <%= select_tag :assignee, options_for_select(User.all.map { |user| [user.name, user.id] }), id: "assignee-#{@task.id}", include_blank: @task.assigned_task&.user&.name.presence || "Add Assignee...",
                          class: 'w-full p-3 focus:outline-none border-slate-200 rounded-md text-sm', selected: @task.assigned_task&.user_id,
                          data: { controller: "tasks", tasks_url_value: assign_project_task_path(@project, @task), "select2-id": "#{dom_id(@task, 'assignee')}" } %>
            <% end %>
          <% end %>
        </div>

        <div class="col-span-1">
          <%= f.label :priority, "Priority", class:'text-base' %>
          <%= f.input :priority, collection: Task::PRIORITIES.map { |key, value| [value, value] },
                        include_blank: "Add Priority...", selected: f.object.priority, label: false, placeholder: 'Enter here',
                        input_html: { class: 'w-full p-3 focus:outline-none border-slate-200 rounded-md text-sm',
                        data: { controller: "select2", "select2-id": "#{dom_id(@task, 'priority')}" } } %>
          <span class="text-error"><%= f.object.errors[:priority].join(", ") %></span>
        </div>

        <div class="col-span-6">
          <%= f.label :description, "Description", class: "text-base" %>
          <%= f.rich_text_area :description, placeholder: "Enter here", class: "w-full h-96", rows: '4' %>
          <span class="text-error"><%= f.object.errors[:description].join(", ") %></span>
        </div>

        <div class="col-span-2 mt-5">
          <%= label_tag :location, "Location", class: "text-base" %>
          <div data-controller="maps">
            <%= text_field_tag :location, {}, data: { "maps-target": "address" }, class: "w-full hidden mt-4 focus:outline-none border-slate-200 rounded-md text-sm" %>
            <div data-maps-target="container" class="h-[25rem] mb-12 w-auto"></div>
          </div>
        </div>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="actions mt-3">
        <%= f.button :button, @task.persisted? ? "Update task" : "Add task", data: { turbo_frame: dom_id(@project) },
            class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded" %>
        <%= link_to  "Cancel", @task.persisted? ? project_task_path(@project, @task) : project_path(@project), data: { turbo_frame: @task.persisted? ? dom_id(@task) : "_top" },
            class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded" %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="bg-gray-100 hover:bg-gray-300 block py-2 px-2  rounded-md my-2">
  <div class="grid grid-cols-8 gap-4">
    <div class="col-span-3">
      <h3 class="font-bold">Title + Description</h3>
    </div>
    <div class="col-span-1">
      <h3 class="font-bold">Assignee</h3>
    </div>
    <div class="col-span-1">
      <h3 class="font-bold">Priority</h3>
    </div>
    <div class="col-span-1">
      <h3 class="font-bold">Location</h3>
    </div>
    <div class="col-span-2">
      <h3 class="font-bold">Attachements</h3>
    </div>
  </div>
  <hr/>
  <div class="grid grid-cols-8 gap-4 mt-1">
    <div class="col-span-3">
      <div class="font-bold">
        <%= task.title %>
        <%= link_to edit_project_task_path(@project, task), data: { class: "hover:bg-inherit visited:text-black hover:bg-inherit visited:bg-inherit", turbo_frame: "#{dom_id(task)}" } do %>
          <span class="ml-2"><i class="fa-solid fa-pencil"></i></span>
        <% end %>
      </div>
      <div class="block">
        <%= task.description.to_plain_text %>
      </div>
    </div>
    <div class="col-span-1">
      <% if task.assigned_task %>
        <%= task.assigned_task.user.name %>
      <% end %>
    </div>
    <div class="col-span-1 -my-1">
      <i class="fa-solid fa-flag text-xl mt-2 <%= priority_color(task.priority) %>"></i>
      <span class="pl-2 pr-3 -my-1 -mt-1 text-base"><%= task.priority.titleize %></span>
    </div>
    <div class="col-span-1 -my-1">
      <% if task.location %>
        <%= task.location.address %>
      <% end %>
    </div>
    <div class="col-span-2">
      <% task.description&.body&.attachments&.each do |attachment| %>
        <% if attachment.image? %>
          <%= image_tag attachment.variant(resize: "300x300") %>
        <% elsif attachment.video? %>
          <%= video_tag url_for(attachment.attachable),
                        preload: "auto",
                        controls: "controls",
                        width: "640",
                        height: "360" %>
        <% else %>
          <figcaption class="attachment__caption">
            <% if caption = attachment.try(:caption) %>
              <%= caption %>
            <% else %>
              <span class="attachment__name"><%= attachment.filename %></span>
              <span class="attachment__size"><%= number_to_human_size attachment.byte_size %></span>
            <% end %>
          </figcaption>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/assign.turbo_stream.erb
<%= turbo_stream.update 'assignee-drop-down' do %>
  <%= label_tag :assignee, "Assignee", class:'text-base' %>
  <%= select_tag :assignee, options_for_select(User.all.map { |user| [user.name, user.id] }), id: "assignee-#{@task.id}", include_blank: @task.assigned_task&.user&.name.presence || "Add Assignee...",
              class: 'w-full p-3 focus:outline-none border-slate-200 rounded-md text-sm', selected: @task.assigned_task&.user_id,
              data: { controller: "tasks", tasks_url_value: assign_project_task_path(@project, @task), "select2-id": "#{dom_id(@task, 'assignee')}" } %>
<% end %>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag dom_id(@task) do %>
  <%= render 'form' %>
<% end %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag 'new_task_section' do %>
  <%= render 'form' %>
<% end %>

app/views/tasks/show.html.erb
<%= turbo_frame_tag dom_id(@task) do %>
  <%= render @task %>
<% end %>